version: '3.1'
services :
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tmart
      POSTGRES_PASSWORD: tmart
      POSTGRES_DB: tmart

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080