# Generated by Django 4.1.3 on 2022-11-24 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogg',
            new_name='Blog',
        ),
    ]
