# Generated by Django 4.1.3 on 2022-11-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogg_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog')),
            ],
        ),
    ]
