# Generated by Django 4.1.3 on 2022-11-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_blog_image_blog_description_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='product_id',
            new_name='blog_id',
        ),
    ]
