# Generated by Django 4.1.3 on 2022-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_product_id_media_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='header',
            field=models.CharField(default=1, max_length=66),
            preserve_default=False,
        ),
    ]
