# Generated by Django 4.1.3 on 2022-11-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_id',
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='product.size'),
            preserve_default=False,
        ),
    ]
