# Generated by Django 4.1.3 on 2022-11-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_size_id_product_size_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_id',
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='product.color'),
            preserve_default=False,
        ),
    ]
