# Generated by Django 4.1.3 on 2022-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_color_id_product_color_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title'),
        ),
    ]
